// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "ade894a66bb4b5c04dc64a75ff6b76e0"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"1e6f24e4f69dbae55b0c788bfe7e9dba": "1f8b08000000000000ff4a322ca9c8283503040000ffff741a8c3707000000",
		"4451b173a3dc44d337e944dfe1348f0b": "1f8b08000000000000ffac90cdaaf3201086f77315c17d4cf2f19523815e490861d449941a15b57f777fb050da6eced99c9dcc3cbccfeb4c540ca51950ebd41c1b664a8963d70dffbe78cf7b3e8c42888181c79deafa413338d17d89584c1da152e1ec0b3fd19d41c49caf21e9ba78be19ecd62f2af8d5a6bd393603c024b3fa74e6b1eb34166c33916e632299553bb479e0d27af48a7848db280eff0fddab8dccea2fbadccc0cf266965f6e50917799bc19fe21acc0bbb4023f886172619bc1d1855cc5ad5f03036d1f1d5cd83283d53a7a7e76c5b3a2c25dd818248a219545a17354f1155da6471edf833e3b9a01a35d32a50ba5a679a54f9eca35a4d30c35a0ce452f7a06df010000ffff54467c6f07020000",
		"b756567d5f452dd062ab17f2000b5691": "1f8b08000000000000ff448f498a1c410c00ffa2731568c9fd374a29859bd99aaa66b019faefa6fa601f254428e207d4fd58e7090318a3865a43b21c265117a3c5545725f329e28d5aa8c00676fcb93fbe60fc80ddeebfd60103749d3b71dbed715c07aff563fd7ec080360b1afa129e29b09851eac2e61115a718d2326332ce61331cd573e3e0e9d435aa09fee3ddf5d08ff37a7bfbbe847b9526bdcda6ec41296ad2469a664e754914786ef0e60103ce9730bcc6ff107f7b5f9f308437f884c18529a50dee3068830346dbe0d4f72b80954b2bddb84c14463693552749a989d5c4a8762935776255116dea3a6952aea94f74f34be4430d06a026cd2cc9a3b4556321a5550cbb91155f524ce6c2868da292b8f44c3c3d1a5bd79211ed22dd1c0650a46069b46b04ed0917eebd51df8b75092c296b99b0c1f73acedbd715f9fc1b0000fffffe9527efeb010000",
		"c1d01ee2d0c0a4b5484da3642fa7e4bc": "1f8b08000000000000ff7451db6a1b410c7dcf572cfb9c859146a399f1dfe832a2264963764d6829fef7b2760889dbbcea70aefaf3304dd334bf8d753bbefe9c0f537ebc5d8e3e1fa6394520b73296084a0b29c5d23ca725c212d4d12507cdef0c715fc7b6edb41c4db583151da82c6a9c938d1e45390652925c31c3f8a0dafafb747e9d0fd32dceed763cfd18eb79fc3aef8a6eca9539412fd5b977e0eeec1154c83374869ab0107036a891b42514c2c06a0e8a06faeef449f924abbc6c5f3c6fc5dfae0dba7a1e50c57b86668e95ac1618ca0a5d52993f48977f9477be8c6d016c8b9dd7cfd64f1e3bba5d0bdf01df05f2a7e771fd0c3e7e053679be6e633892961e9d4d72a750f794aaf14077b2e02ed5d5eabe58a494408d1cc8aae570ccdae63bdddd0c1981e80ed89bb5bbdb693e4cf0df315ec4f674981be6c6ad5a6816062d89b80fe0ca5ab0c9c09ca20b0a67d63a82b2542a4e58d0c513de96be3c5cfe060000ffff8f4c66a3ab020000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("../../config", "../../config")
		b.SetResolver("account.key", packr.Pointer{ForwardBox: gk, ForwardPath: "b756567d5f452dd062ab17f2000b5691"})
		b.SetResolver("bxh.account.key", packr.Pointer{ForwardBox: gk, ForwardPath: "c1d01ee2d0c0a4b5484da3642fa7e4bc"})
		b.SetResolver("bxh.password", packr.Pointer{ForwardBox: gk, ForwardPath: "1e6f24e4f69dbae55b0c788bfe7e9dba"})
		b.SetResolver("faucet.toml", packr.Pointer{ForwardBox: gk, ForwardPath: "4451b173a3dc44d337e944dfe1348f0b"})
	}()
	return nil
}()
